[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
saturn_v1_lite = "EhpHsXFKaD6DtPwoveCedCYcPJWk8ZJd1HmSFE7MebPU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


